- defaults:
    link:
      create: true
      relink: true
      force: true
- clean:
    - ~/.config/bash
- link:
    ~/.bash_profile: shells/bash/bash_profile
    ~/.profile: shells/bash/profile.osx
    ~/.bashrc: shells/bash/bashrc
    ~/.bash_aliases: shells/bash/bash_aliases.osx
    ~/.config/bash/.bash_prompt: shells/bash/config/bash/bash_prompt
    ~/.config/bash/sensible.bash: shells/bash/config/bash/sensible.bash
    ~/.config/bash/bashmarks.sh: shells/bash/config/bash/bashmarks.sh
- brew: [bash]
