- defaults:
    link:
      create: true
      relink: true
      force: true
- clean:
    - ~/.config/fisherman
    - ~/.config/fish
- link:
    ~/.config/fish/abbr.fish: shells/fish/config/fish/abbr.linux.fish
    ~/.config/fish/autoenv.fish: shells/fish/config/fish/autoenv.fish
    ~/.config/fish/config.fish: shells/fish/config/fish/config.fish
    ~/.config/fish/completions/fisher.fish: shells/fish/config/fish/completions/fisher.fish
    ~/.config/fish/functions/edit_config_fish.fish: shells/fish/config/fish/functions/edit_config_fish.fish
    ~/.config/fish/functions/gls.fish: shells/fish/config/fish/functions/gls.fish
    ~/.config/fish/functions/git.fish: shells/fish/config/fish/functions/git.fish
    ~/.config/fish/functions/gitv.fish: shells/fish/config/fish/functions/gitv.fish
    ~/.config/fish/functions/l.fish: shells/fish/config/fish/functions/l.fish
    ~/.config/fish/functions/la.fish: shells/fish/config/fish/functions/la.fish
    ~/.config/fish/functions/ll.fish: shells/fish/config/fish/functions/ll.fish
    ~/.config/fish/functions/ls.fish: shells/fish/config/fish/functions/ls.fish
    ~/.config/fish/functions/psa.fish: shells/fish/config/fish/functions/psa.fish
    ~/.config/fish/functions/search_history.fish: shells/fish/config/fish/functions/search_history.fish
    ~/.config/fish/fishfile: shells/fish/config/fish/fishfile.linux
    ~/.config/fish/functions/fisher.fish: shells/fish/config/fish/functions/fisher.fish
    ~/.config/fish/functions/fish_greeting.fish: shells/fish/config/fish/functions/fish_greeting.fish
    ~/.config/fish/functions/fish_mode_prompt.fish: shells/fish/config/fish/functions/fish_mode_prompt.fish
    ~/.config/fish/functions/fish_prompt.fish: shells/fish/config/fish/functions/fish_prompt.fish
    ~/.config/fish/functions/fish_right_prompt.fish: shells/fish/config/fish/functions/fish_right_prompt.fish
    ~/.config/fish/functions/fish_title.fish: shells/fish/config/fish/functions/fish_title.fish
- shell++:
    - - fish -c 'fisher and fisher up'
      - Installing fisher plugins
- link:
    ~/.config/fish/functions/fisher.fish: shells/fish/config/fish/functions/fisher.fish
    ~/.config/fish/functions/fish_user_key_bindings.fish: shells/fish/config/fish/functions/fish_user_key_bindings.linux.fish
