---
- defaults:
    link:
      create: true
      relink: true
      force: true
- clean:
  - "~"
  - "~/.config"
- shell:
  - description: Update submodules in dotfiles repo
    command: |
      git submodule update --init --recursive
